package bme.youronebackend.person

import java.time.LocalDate

data class PersonAllDTO(
    var username: String?,
    var name: String,
    var email: String,
    var photo: String,
    var birthDate: LocalDate,
    var height: Int? = null,
    var age: Int? = null,
    var gender: Int? = null,
    var tattoo: Int? = null,
    var eyeColour: Int? = null,
    var hairColour: Int? = null,
    var piercing: Int? = null,
    var glasses: Int? = null,
    var beard: Int? = null,
    var sportiness: Int? = null,
    var breastSize: Int? = null,
    var bio: Int? = null,
    var city: Int? = null,
    var jobType: Int? = null,
    var eduLevel: Int? = null,
    var cigarettes: Int? = null,
    var alcohol: Int? = null,
    var childrenNumber: Int? = null,
    var maritalStatus: Int? = null,
    var musicalTaste: Int? = null,
    var filmTaste: Int? = null,
    var religion: Int? = null,
    var horoscope: Int? = null,
    var languages: Int? = null,
    var interests: Int? = null,
)