version: '3'

services:
  yodb:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: yodb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - backdb
    expose:
      - 5432
    restart: always

  yourone-backend:
    container_name: yourone-backend
    image: yourone-backend:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8040:8040
    depends_on:
      - yodb
    networks:
      - backdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://yodb:3306/yodb





volumes:
  postgres:


networks:
  backdb:
    driver: bridge